#!/bin/sh

time_path="$HOME/.local/share/flowtimer/"

if [ "$1" = "start" ]; then
  echo $(date '+%s') > ${time_path}time
  notification.sh -t "Timer started!"
elif [ "$1" = "break" ]; then
  old_time=$(cat ${time_path}time)
  new_time=$(date '+%s')
  break_time=$(awk -v o_time="$old_time" -v n_time="$new_time" -v div="$divider" 'BEGIN{print int(n_time - o_time) / 5}')
  awk -v b_time="$break_time" 'BEGIN{print "You have " int(b_time) / 60 " Minutes"}'
  sowon $break_time"s"
elif [ "$1" = "show" ]; then
  old_time=$(cat ${time_path}time)
  new_time=$(date '+%s')
  work_time=$(awk -v o_time="$old_time" -v n_time="$new_time" -v div="$divider" 'BEGIN{print int(n_time - o_time)}')
  awk -v w_time="$work_time" 'BEGIN{print "You worked for " int(w_time) / 60 " Minutes"}'
else
  echo "You can start the flowtimer using 'flowtimer start'\nYou can take a break using 'flowtimer break'\nYou can see how long you worked for using 'flowtimer show'"
fi
