#!/bin/sh

process=$(ps -u $USER -o pid,comm,%cpu,%mem --sort size | sed -n '1!p' | dmenu -i -l 15 -p "Kill:")
pid=$(echo $process | awk '{print $1}')
cmd=$(echo $process | awk '{print $2}')
if [ $cmd ]; then
  kill -15 $pid 2>/dev/null
  notification.sh -t "Killed $cmd"
fi
