#!/bin/sh

directory="$(tmux display-message -p '#{pane_current_path}')"
branch_name=$(basename ${directory})
session_name=$(tmux display-message -p "#S")
clean_name=$(echo $branch_name | tr "./" "__")
target="$session_name:$clean_name"

if ! tmux has-session -t $target 2> /dev/null; then
    tmux neww -dn $clean_name -c "$directory"
fi
