#!/bin/sh

site=$(cat $HOME/.dotfiles/scripts_share/bookmarks.txt | awk '{print $1}' | wofi -id -L 10 -p "Visit website")
query=$(cat $HOME/.dotfiles/scripts_share/bookmarks.txt | grep $site | awk '{print $2}')
if [ $query ]; then
  $(cat $HOME/.dotfiles/scripts_share/browser.txt) "$query"
fi
